name: Prevent Provision Directory Changes

on:
  pull_request:
    branches:
      - main
      - 'release_*'

jobs:
  verify-changed-files:
    if: ${{ github.actor != 'github-actions[bot]' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get list of changed files and check for unauthorized changes
        uses: actions/github-script@v7
        with:
          script: |
            const { data: commits } = await github.rest.pulls.listCommits({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number
            });

            for (const commit of commits) {
              const { data: files } = await github.rest.repos.getCommit({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: commit.sha
              });

              const changedFiles = files.files.map(file => file.filename);
              console.log(`Changed files in commit ${commit.sha}:`, changedFiles);

              const unauthorizedChanges = files.files.some(file => 
                (file.filename.startsWith('provision/libs/') || file.filename.startsWith('provision/headers/')) && 
                file.additions > 0 && file.deletions > 0 && commit.author.login !== 'github-actions[bot]'
              );

              if (unauthorizedChanges) {
                core.setFailed(`Unauthorized changes detected in the provision directory by ${commit.author.login} in commit ${commit.sha}`);
                break;
              }
            }