name: Prevent Provision Directory Changes

on:
  pull_request:
    branches:
      - main
      - 'release_*'

jobs:
  verify-changed-files:
    if: ${{ github.actor != 'github-actions[bot]' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check for changes in provision directory
        shell: bash
        run: |
          if git diff --name-only ${{ github.base_ref }} ${{ github.ref }} | grep '^provision/'; then
            echo "Unauthorized changes detected in the provision/ directory by ${{ github.actor }}"
            exit 1
          fi
