name: Publish provisioning Libraries
on:
  repository_dispatch:
    types: [trigger-publish-provisioning-libs]
  workflow_dispatch:
    
permissions:
  contents: write
  pull-requests: write

jobs:
  publish-libs:
    if: startsWith(github.event.client_payload.branch, 'release_') || github.event.client_payload.branch == 'main'
    runs-on: ubuntu-latest

    concurrency:
      group: ${{ github.event.client_payload.branch }}-publish-provisioning-libs
      cancel-in-progress: true

    env:
      PLATFORMS: '["MG24", "MGM24", "MG26", "SI917", "SI917_PSA"]'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.client_payload.branch }}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          
      # Used in the javascript code
      - name: Install required packages
        run: npm install unzipper @actions/core @actions/github

      - name: Download Built Libraries
        uses: actions/github-script@v7
        env:
          PLATFORMS: ${{ env.PLATFORMS }}
          BRANCH: ${{ github.event.client_payload.branch }}
        with:
          github-token: ${{ secrets.WORKFLOW_TOKEN }}
          script: |
            const platforms = JSON.parse(process.env.PLATFORMS);
            const provisioningRepo = 'matter_provisioning';
            const branch = process.env.BRANCH;
            const { downloadAndExtractArtifact } = require('./.github/actions/download-artifact/downloadAndExtractArtifact.js');

            for (const platform of platforms) {
              const downloadPath = path.join(process.env.GITHUB_WORKSPACE, 'matter_support/provision/lib');
              const filePath = path.join(downloadPath, `built-libraries-${platform}.zip`);
              await downloadAndExtractArtifact(`built-libraries-${platform}`, downloadPath, filePath, provisioningRepo, branch);
            }

      - name: Download Headers
        uses: ./.github/actions/download-artifact
        with:
          artifact-name: headers
          download-path: ${{ github.workspace }}/matter_support/provision/headers
          file-path: ${{ github.workspace }}/matter_support/provision/headers/headers.zip
          provisioning-repo: matter_provisioning
          branch: ${{ github.event.client_payload.branch }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: automation/update_${{ github.event.client_payload.branch }}_provisioning
          base: ${{ github.event.client_payload.branch }}
          title: "Update provisioning libraries and headers for ${{ github.event.client_payload.branch }}"
          body: "This PR updates the provisioning libraries and headers for the ${{ github.event.client_payload.branch }} branch."
          commit-message: "Update provisioning libraries and headers"
          author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          committer: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          add-paths: 'matter_support/provision'